# Deploy cloud - IBM Code Engine (Nuxt app)
name: App Nuxt - Deploy to IBM Cloud Code Engine
permissions:
  contents: read
on:
  # Trigger on push to main
  push:
    branches: [main]
    paths:
      - 'apps/hello-carbon-nuxt/**'
      - '.github/workflows/app-nuxt-deploy.yml'

  # Manual run
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          # Use the Nuxt app's .nvmrc to select Node version
          node-version-file: "apps/hello-carbon-nuxt/.nvmrc"

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Install Code Engine and Container Registry plugins
        run: |
          ibmcloud plugin install code-engine
          ibmcloud plugin install container-registry

      - name: Show IBM CLI version
        run: ibmcloud -v

      - name: Login to IBM Cloud
        env:
          IBM_CLOUD_APIKEY: ${{ secrets.IBM_CLOUD_APIKEY }}
          IBM_CLOUD_GROUP: ${{ vars.IBM_CLOUD_GROUP }}
          IBM_REGION: ${{ vars.IBM_REGION }}
          IBM_CR_REGION: ${{ vars.IBM_CR_REGION }}
        run: |
          ibmcloud login --apikey ${IBM_CLOUD_APIKEY} -g ${IBM_CLOUD_GROUP} -r ${IBM_REGION}
          ibmcloud cr region-set ${IBM_CR_REGION}
          ibmcloud cr login

      - name: Build and push docker image (Nuxt app)
        working-directory: apps/hello-carbon-nuxt
        env:
          CE_PROJECT: ${{ vars.CE_PROJECT }}
          CE_APP_NAME: ${{ vars.CE_APP_NAME }}
          CE_SCALE_DOWN_DELAY: ${{ vars.CE_SCALE_DOWN_DELAY }}
          CR_IMAGE: ${{ vars.CR_IMAGE }}
        run: |
          cp ../../package-lock.json .
          IMAGE_TAG=$(date '+%FT%H%M%S')
          docker build -t ${CR_IMAGE}:$IMAGE_TAG .
          docker push ${CR_IMAGE}:$IMAGE_TAG
          ibmcloud ce project select --name ${CE_PROJECT}
          ibmcloud ce app logs --tail 5 --follow --name ${CE_APP_NAME} &
          ibmcloud ce app update --image private.${CR_IMAGE}:$IMAGE_TAG --scale-down-delay ${CE_SCALE_DOWN_DELAY} --name ${CE_APP_NAME}
