name: App Nuxt - CI
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/hello-carbon-nuxt/**'
      - '.github/workflows/app-nuxt-ci.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Use root lock file
        run: cp package-lock.json apps/hello-carbon-nuxt/
      - name: Build docker image
        working-directory: apps/hello-carbon-nuxt
        run: docker build -t pr:testing .
      - name: Install dependencies
        working-directory: apps/hello-carbon-nuxt
        run: npm install
      - name: lint
        working-directory: apps/hello-carbon-nuxt
        run: npm run lint
      - name: Build app
        working-directory: apps/hello-carbon-nuxt
        run: npm run build
