name: End-to-end tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm i -g pnpm@10
      - name: Install dependencies
        env:
          DEBUG: "cypress:cli*"
          CYPRESS_CACHE_FOLDER: '~/.cache/Cypress'      
        run: |
          echo "node-linker=hoisted" > .npmrc
          pnpm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          DEBUG: "cypress:cli*"
          CYPRESS_CACHE_FOLDER: '~/.cache/Cypress'
        with:
          install: false
          start: pnpm run dev
          browser: ${{ matrix.browser }}
