name: End-to-end tests
permissions:
  contents: read
  pull-requests: write
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run dev:build
          start: npm run dev:preview
          browser: ${{ matrix.browser }}
