name: Greetings
permissions:
  contents: read
  pull-requests: write
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you so much for contributing to our work!'
        pr-message: 'Thank you for your contribution! Someone will review it ASAP.'
