name: Greetings
permissions:
  contents: read
  pull-requests: write
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Thank you so much for contributing to our work!'
        pr_message: 'Thank you for your contribution! Someone will review it ASAP.'
