name: Deploy to GitHub Pages (multi-app)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/hello-carbon11-vue3/**'
      - 'apps/hello-carbon-vue3/**'
      - '.github/workflows/pages-build.deployment.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies (workspace root)
        run: npm install
      - name: Build hello-carbon-vue3
        working-directory: apps/hello-carbon-vue3
        run: npm run build
      - name: Build hello-carbon11-vue3
        working-directory: apps/hello-carbon11-vue3
        run: npm run build
      - name: Prepare dist folder structure
        run: |
          rm -rf dist
          mkdir -p dist/hello-carbon-vue3
          mkdir -p dist/hello-carbon11-vue3
          cp -r apps/hello-carbon-vue3/dist/* dist/hello-carbon-vue3/
          cp -r apps/hello-carbon11-vue3/dist/* dist/hello-carbon11-vue3/
          # Create top-level navigation index.html
          cp common/ghpages/index.html dist/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
